### ISSUE TITLE
Migrate to Debian bullseye

### ISSUE THREAD

**Issue by thiagokokada** [Quantisan/docker-clojure#116]
The images currently use Debian 10 (`buster`) as base, however Debian 11 was recently released: https://www.debian.org/News/2021/20210814

So it would be interesting to have the images be based on the newest Debian, so we can get updated libraries.

**Comment by thiagokokada** [comment]
Related issue: https://github.com/babashka/babashka/issues/866

**Comment by cap10morgan** [comment]
This will require that our upstream openjdk images release bullseye-based tags. Once they release those, we’ll add bullseye tags in here.

**Comment by thiagokokada** [comment]
@cap10morgan It seems upstream finally has bullseye available: https://github.com/docker-library/openjdk/commit/ac338f3112ad10269fc2d21d9104570454ca064b

Example image: https://hub.docker.com/layers/openjdk/library/openjdk/11-bullseye/images/sha256-2a5d07a70334b059999d099d3211b9eeca58eefff9ff027b56b53c677bc9fed5

**Comment by cap10morgan** [comment]
OK re-opening now that this is back in our court. Thanks @thiagokokada!
