### ISSUE TITLE
Please add git - tools.deps supports git versions and need git client to download them

### ISSUE THREAD

**Issue by ieugen** [Quantisan/docker-clojure#119]
Hello,

I have a deps.edn that I can't use with `FROM clojure:openjdk-11-tools-deps-slim-buster`  since it's missing `git` client.

It would be great to have git available by default in these images. 

I get
```
Cloning: https://github.com/clojure/tools.build.git
Error building classpath. Cannot run program "git": error=2, No such file or directory
java.io.IOException: Cannot run program "git": error=2, No such file or directory
```

deps.edn
```clojure
{:paths ["src"]
 :deps {io.github.ieugen/deps-deploy {:git/sha "4979c17f5e8c42330528c011e626160c85dabd69"}} 
 }
 ```

**Comment by cap10morgan** [comment]
@ieugen Thanks for reporting. I remember they recently switched from using libgit2 to just running the git command. It didn’t occur to me that we would need to add it into this image then. 😆

I’ll get on this.
