### ISSUE TITLE
onbuild is not a valid tag on Docker Hub

### ISSUE THREAD

**Issue by rxacevedo** [Quantisan/docker-clojure#13]
Hi there @Quantisan, I'm not sure if this is intended or not, but `onbuild` is not currently a valid tag in Docker Hub. One can, of course, clone this repository and run `docker build --rm -t clojure:onbuild onbuild` as instructed in the README to create an image in one's own registry, but this will cause build failures on Docker Hub, since the tag does not exist there. So while I can build `clojure:onbuild` locally and then build descendant images against it, that same image would not build on Docker Hub or Quay. Just wanted to let you know - thanks!

**Comment by Quantisan** [comment]
@rxacevedo thanks for noticing. I've submitted a pull request to add `onbuild` to the Hub. https://github.com/docker-library/official-images/pull/957

**Comment by rxacevedo** [comment]
Thanks @Quantisan! Much appreciated - I'll close this issue since I've subscribed to the other one. :+1:
