### ISSUE TITLE
`openjdk-8-tools-deps` images are outdated for `arm64v8`

### ISSUE THREAD

**Issue by otwieracz** [Quantisan/docker-clojure#132]
Most recent image for `arm64v8/openjdk-8-tools-deps` is currently two years old and is built with Clojure version `1.10.0.442` where other images for other JDK versions are at `1.10.3.967`:
https://hub.docker.com/r/arm64v8/clojure/tags?page=1&ordering=last_updated&name=openjdk-8-tools-deps

Is there any reason why those images are no longer produced and is this possible to keep supporting OpenJDK 8 here?

**Comment by cap10morgan** [comment]
I think the necessary upstream openjdk images used to not be available and/or supported. But they appear to be available and supported now, so I've removed the architecture restriction on those in this PR: https://github.com/docker-library/official-images/pull/10934

**Comment by cap10morgan** [comment]
Oddly I may need to wait on #126 to be merged to move this forward. I need to pull in a public key for leiningen and that's annoyingly difficult w/o using the "prereqs" feature I added in that PR.

**Comment by cap10morgan** [comment]
This should be fixed now (or very shortly once the new automated builds complete): https://github.com/docker-library/official-images/pull/10934
