### ISSUE TITLE
make latest available as tagged image

### ISSUE THREAD

**Issue by bluebrown** [Quantisan/docker-clojure#147]
Hi, I think it would be good to have what is latest, the combination of all tags with boot, leningen and tools-dep, as tagged version available.

I am using latest for multi staging as builder base, but it doesn't feel sound to not version pin it. Currently, I do not see an option, besides installing some dependencies by hand.

**Comment by cap10morgan** [comment]
@bluebrown Can you explain your use case in a little more detail? And specifically why you can't (easily) use the separate versioned tool-specific images?

**Comment by bluebrown** [comment]
In my case, it was missing make in the lein version.

```Dockerfile
FROM clojure:openjdk-17-lein-buster as builder

# needed to add this, since make is not available in lein
RUN apt-get update -y && apt-get install make 

WORKDIR /src
COPY . ./
RUN make libs && make


FROM openjdk:17-slim-buster
...
```

**Comment by cap10morgan** [comment]
Yeah, and the `latest` tag only has `make` because it was commonly being used by tools.deps projects and `latest` includes the tools.deps stuff.

I think we could probably add `make` to the non-slim lein and boot variants too. That's a reasonable thing for a programming language image to have. What do you think, @Quantisan?

**Comment by Quantisan** [comment]
sounds good to add `make` to non-slim variants @cap10morgan

**Comment by cap10morgan** [comment]
https://github.com/docker-library/official-images/pull/11580 was just merged so non-slim lein and boot variants w/ make pre-installed should show up on Docker Hub soon. @bluebrown does this solve your issue?

**Comment by bluebrown** [comment]
Yes, I guess this  will cover my use case. Thank you for doing this and taking swift action.
