### ISSUE TITLE
Move some or all of our base images off of openjdk

### ISSUE THREAD

**Issue by cap10morgan** [Quantisan/docker-clojure#159]
[Oracle is at it again](https://github.com/docker-library/openjdk/pull/495) and we'll have to move some or all of our base images off of the `openjdk` ones. Version 17+ at the very least. But I'm kind of inclined to just move everything to the new one we decide on. The consistency will be easier to implement and maintain over time, and Clojure isn't _that_ sensitive about which JDK it's running on (so hopefully wouldn't break backwards compatibility).

Please leave comments, questions, and new base JDK image suggestions (with some "why") below in comments!

**Comment by cap10morgan** [comment]
The biggest source of breakage and disruption here will be the underlying Linux distro used by the upstream image. A quick check reveals that Eclipse Temurin is based on Ubuntu (likely mild breakage but more than I'd like) and Amazon Corretto is (of course) based on Amazon Linux (RPM-based distro; massive breakage).

Anyone aware of a not-too-exotic JDK distribution whose official Docker images are Debian-based? I'll keep looking too.

**Comment by cap10morgan** [comment]
If we can't find a new Debian-based official image to move to then we may have to keep Java 8 & 11 images where they're at for now (which from what I can tell is still going to be supported). I wouldn't want to force any more of that kind of breakage than is absolutely necessary.

**Comment by cap10morgan** [comment]
One of the Docker official image maintainers [posted a good reason to move everything over to a new upstream image](https://github.com/docker-library/openjdk/pull/495#issuecomment-1112457478) (i.e. not just Java 17+).

On the other hand, we could leave Java 8 & 11 alone and just let them age out once they're EOL'd.

Thoughts?

**Comment by cap10morgan** [comment]
One saving grace with switching distros is that because we have those in the tag names (at least for those following our long-standing advice of including every element they rely on in the tag they pull from), this change will be opt-in.

**Comment by Quantisan** [comment]
> If we can't find a new Debian-based official image to move to then we may have to keep Java 8 & 11 images where they're at for now (which from what I can tell is still going to be supported). I wouldn't want to force any more of that kind of breakage than is absolutely necessary.

I'm with you on not forcing anymore breakage than necessary. You're right that 8 and 11 might get stale and we'll need to move them over sooner or later. (FYI 11's EOL is in 2026) But perhaps we can just migrate 17 for now and let folks get used to that before moving the rest over?

There's no clear choice here so I'll leave it to you to decide, @cap10morgan. We should make an announcement though if we're to move 8 and 11 so people using the old images at least have a chance to hear that their base images won't be updated at all anymore.

**Comment by cap10morgan** [comment]
Closing this now since #160 has landed and #161 will soon most likely. :)
