### ISSUE TITLE
docker clojure build error: exec: "/bin/sh": stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by wqhhust** [Quantisan/docker-clojure#17]
I have the following error. How to fix it?
oracle@SomeHost ~/clojure/lein/test $ docker build -t my-clojure-app .
Sending build context to Docker daemon 39.94 kB
Step 1 : FROM clojure
 ---> bebbadd1af50
Step 2 : RUN mkdir -p /usr/src/app
 ---> Running in c2522bfe4047
exec: "/bin/sh": stat /bin/sh: no such file or directory
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

oracle@SomeHost ~/clojure/lein/test $ cat Dockerfile 
FROM clojure
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app/
RUN lein deps
COPY . /usr/src/app
RUN mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app-standalone.jar
CMD ["java", "-jar", "app-standalone.jar"]

oracle@SomeHost ~/clojure/lein/test $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17 Qiana
Release:	17
Codename:	qiana
oracle@SomeHost ~/clojure/lein/test $ docker -a
flag provided but not defined: -a
See 'docker --help'.
oracle@SomeHost ~/clojure/lein/test $ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
oracle@SomeHost ~/clojure/lein/test $ docker info
Containers: 1
Images: 64
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 8
Total Memory: 7.427 GiB
Name: SomeHost
ID: NTH7:BKQD:XMKF:UERI:UHNF:M3K6:QNJV:ZDRS:LBMX:534M:CJAV:RCFT
WARNING: No swap limit support
oracle@SomeHost ~/clojure/lein/test $

**Comment by Quantisan** [comment]
I can't reproduce it.

```
$ docker build -t my-clojure-app .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM clojure
 ---> bebbadd1af50
Step 2 : RUN mkdir -p /usr/src/app
 ---> Running in df410fcef28a
 ---> e0217f74a8e4
Removing intermediate container df410fcef28a
Step 3 : WORKDIR /usr/src/app
 ---> Running in 16aca9500fbc
 ---> 114a9d11aae3
Removing intermediate container 16aca9500fbc
Successfully built 114a9d11aae3
```

Does Docker work with your other projects on the same machine? Are you using docker-machine or running docker directly from your host machine?

**Comment by Quantisan** [comment]
There's this, perhaps it might help you? https://github.com/docker/docker/issues/5135

**Comment by Quantisan** [comment]
@wqhhust haven't heard from you on this. So I assume that it's not an issue anymore.
