### ISSUE TITLE
git is missing from tools-deps images - regression

### ISSUE THREAD

**Issue by ieugen** [Quantisan/docker-clojure#183]
Hi, 

I opened this issue a while ago and it was fixed but I think it regressed:
https://github.com/Quantisan/docker-clojure/issues/119

I have a `deps.edn` with some git libraries and it's failing with missing git.

A repro is in this git repo: https://github.com/sandre1/clj-training/tree/main/htmx-demo .

I am aslo trying to build for arm64 on amd64 and I could not do this using clojure:temurin-17-tools-deps-bullseye . 
I had to use clojure:temurin-11-tools-deps-bullseye . 
I am still investigating this but it might be an issue with the image (some jlink changes from 11-> 17). 

I will come back once I know more.

**Comment by cap10morgan** [comment]
Fix will be live shortly after this is merged: https://github.com/docker-library/official-images/pull/13829
