### ISSUE TITLE
Can we get temurin 20 images?

### ISSUE THREAD

**Issue by seancorfield** [Quantisan/docker-clojure#191]
We're starting to test locally with Temurin JDK 20 and it would be nice to update our CI pipeline to use `clojure:temurin-20-tools-deps` (we're on `clojure:temurin-19-tools-deps` right now).

**Comment by dharrigan** [comment]
Yes please, I'm on JRE 20 locally, so would be awesome to have images build with Java 20 too please. Thank you.

**Comment by seancorfield** [comment]
> How long has version 20 been out?
A week 😄

**Comment by cap10morgan** [comment]
Still working on getting Temurin 20 images ready. Boot variants are acting up (does anyone still use boot?), so I'm having to filter them out of the build matrix.

As far as upstream release notifications go, [there's a little work to do upstream](https://github.com/adoptium/adoptium-support/issues/751).

**Comment by seancorfield** [comment]
I wouldn't consider Boot very important at this point: it hasn't had a release for four years now and it hasn't even had any source updates for two years.

(I say this as an ex-Boot user: we switched from Leiningen to Boot at work in 2015, but switched to the Clojure CLI in 2018, due to bugs in Boot)
