### ISSUE TITLE
Bad credentials error opening docker-library PR in GitHub Actions

### ISSUE THREAD

**Issue by cap10morgan** [Quantisan/docker-clojure#206]
@Quantisan any idea if anything changed here? https://github.com/Quantisan/docker-clojure/actions/runs/5953103640/job/16146611072

I'm getting a "Bad credentials" error when it tries to open the docker-library PR in GitHub Actions.

**Comment by Quantisan** [comment]
The old token expired but I've updated it now. Try again? I've also set this new token as never expire, so it should be good from now. Sorry about that!

**Comment by cap10morgan** [comment]
Great, thanks! I already did a manual upstream PR for this one, but there will be more. :)
