### ISSUE TITLE
How should we deal with Docker Hub's inability to handle this?

### ISSUE THREAD

**Issue by cap10morgan** [Quantisan/docker-clojure#29]
Well this is disappointing: https://github.com/docker-library/official-images/pull/2511#pullrequestreview-15404410

It sounded like this would be possible to do in official images, but not yet I guess.

Given all that, @Quantisan, should we revert master to where it was before #28 & #27 were merged?

Then I can start on another attempt that will work with their official image building infrastructure.

**Comment by Quantisan** [comment]
@cap10morgan thanks dude!

**Comment by cap10morgan** [comment]
Merging #30 & #31 should accomplish the revert.

**Comment by Quantisan** [comment]
👍
