### ISSUE TITLE
Long-running uberjar creation

### ISSUE THREAD

**Issue by neverfox** [Quantisan/docker-clojure#34]
```bash
# steps to recreate
lein new app docker-lein-uberjar
docker run -it --rm -v $(pwd)/docker-lein-uberjar:/checkout -w /checkout clojure:alpine lein uberjar

# output
Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.pom from central
Retrieving org/sonatype/oss/oss-parent/7/oss-parent-7.pom from central
Retrieving org/clojure/clojure/1.8.0/clojure-1.8.0.jar from central
Compiling docker-lein-uberjar.core
Created /checkout/target/uberjar/docker-lein-uberjar-0.1.0-SNAPSHOT.jar
# Very long pause, compared to directly running on Mac (which is nearly instant)
Created /checkout/target/uberjar/docker-lein-uberjar-0.1.0-SNAPSHOT-standalone.jar
```

Using Docker for Mac 17.05.0-ce-mac11 (17656)

Furthermore, for non-trivial codebases, that long pause is effectively forever, in that I usually give up after 15 minutes.

**Comment by cap10morgan** [comment]
@neverfox Thanks for the bug report! I was able to reproduce this. However, I'm not sure it's anything we can fix. It seems to be a Docker or Docker for Mac bug related to host-mounted volumes. If I just build an image where I copy in this app template output and then run `lein uberjar` on that, it's pretty much instant.

I'll see if I can try it in a pure Linux Docker environment (i.e. no Docker for Mac involved) and see if it happens there. But feel free to beat me to it. 😄

**Comment by cap10morgan** [comment]
My esteemed colleague @gws tried this in a pure Linux Docker environment and could not reproduce it there. So that leads me to believe that this should be reported to the Docker for Mac devs, @neverfox.

**Comment by neverfox** [comment]
@cap10morgan You're probably correct. Thanks for taking the time to investigate it. I actually did the same thing you did after posting this, i.e. compare copying the source to the image vs host-mounted volume and the difference was night and day. In the host-mounted case, I confirmed the uberjar was actually creating but very slowly.

**Comment by neverfox** [comment]
Probably related to [this](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/273).
