### ISSUE TITLE
Boot{,-bin} 2.7.2 is out

### ISSUE THREAD

**Issue by SevereOverfl0w** [Quantisan/docker-clojure#36]
There's a new boot-bin and a new boot out, 2.7.2!

**Comment by cap10morgan** [comment]
Upstream PR to update the official image: https://github.com/docker-library/official-images/pull/3344

**Comment by Deraen** [comment]
@cap10morgan Old boot-bin is still used: 

https://github.com/Quantisan/docker-clojure/blob/master/Dockerfile-boot.template#L16
Should be https://github.com/boot-clj/boot-bin/releases/download/2.7.2/boot.sh

**Comment by cap10morgan** [comment]
Thanks @Deraen. I'll get that fixed soon.

**Comment by cap10morgan** [comment]
New upstream PR: https://github.com/docker-library/official-images/pull/3351

**Comment by cap10morgan** [comment]
This should be fully released now: https://github.com/docker-library/official-images/pull/3351
