### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [Quantisan/docker-clojure#37]
I want to build this image on arm64 architecture, but I'm not sure this tar.gz file and zip packages can be support arm64

**Comment by cap10morgan** [comment]
I'm afraid I don't have access to any arm64 hardware to test this on. Can you provide more details about what we would need to do to support this?

**Comment by longquan7** [comment]
@cap10morgan To be support other architecture you can look like this https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by Quantisan** [comment]
would it be as simple as using `https://hub.docker.com/r/arm64v8/alpine/` and then apply the same Dockerfile in our alpine folder? @longquan7, do you want to give it a try?

**Comment by longquan7** [comment]
@cap10morgan @Quantisan OK, I will try to build on arm64

**Comment by tianon** [comment]
For official images, we prefer to not have multiple architecture `Dockerfile`s, especially given that we anticipate fixing https://github.com/docker-library/official-images/issues/2289 soon.

In the case of Alpine, multi-architecture support is waiting on https://github.com/gliderlabs/docker-alpine/issues/304.

Given that the current `Dockerfile` is essentially just `FROM openjdk`, `wget some-jar-file.jar`, it should work as-is on many architectures in addition to `arm64v8`.  I'm going to do some testing and send a PR for your approval to https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/clojure if it works out. :+1:

**Comment by tianon** [comment]
PR filed at https://github.com/docker-library/official-images/pull/3408 :+1:
