### ISSUE TITLE
Publish 2.8.1; 2.8.0 has serious exit code flaw

### ISSUE THREAD

**Issue by technomancy** [Quantisan/docker-clojure#39]
This could cause severe problems in CI: https://github.com/technomancy/leiningen/issues/2342

Would be great if we could get 2.8.1 published quickly.

**Comment by cap10morgan** [comment]
@technomancy Thanks for the heads up! I'll get the process started.

**Comment by cap10morgan** [comment]
Updated in b4e548bbaab978eaa8e0f4b31705c43526202d3c. Will open a PR to have Docker Hub update it now.

**Comment by technomancy** [comment]
Thanks for the quick response.

**Comment by cap10morgan** [comment]
[official-images PR](https://github.com/docker-library/official-images/pull/3645) merged. Should appear on the hub shortly.
