### ISSUE TITLE
Don't run as root

### ISSUE THREAD

**Issue by ToBeReplaced** [Quantisan/docker-clojure#4]
How about having a user 'lein'?

**Comment by ToBeReplaced** [comment]
@Quantisan - You need to fix this. It is your obligation as the owner to plug known security holes or responsibly drop your "official image" status.

I don't have any use for this image, so I will not do the work to fix it.

**Comment by md5** [comment]
@ToBeReplaced Your attitude is not helpful. Don't be a :eggplant:

**Comment by ToBeReplaced** [comment]
@md5 - How could I have better conveyed the message?

**Comment by md5** [comment]
@ToBeReplaced I'm not sure, but it just seemed rude to come back to this issue after almost six months and make an accusatory comment demanding action from @Quantisan. It's fine if you don't want to create a PR yourself, but I don't see what it achieves to throw that in people's faces.

I personally don't consider the `clojure` image running as `root` to be a security hole. Running as `root` is common to all the language base images in the Docker official images library. If this were an image for a particular app or service, I'd be more likely to consider it an actual security flaw. In fact, I've made updates to the `jetty` image and been involved in the discussion around a number of other official images to make them run as non-`root` users.

**Comment by ToBeReplaced** [comment]
I guess I view it differently. I believe that if you maintain an open source project with the intent for others to use it, you have a moral obligation to fix known security issues.

I saw this image when it was released, and posted an issue in hopes that before anyone started using it, the leak would be resolved. I checked up on my issue months later, and saw it was never resolved. So, I brought up that either the owner should fix it, or stop users from using the image by requesting to drop its official image status. This would allow for someone more interested in maintaining an image for clojure to step in (or in this case, actually leiningen, since clojure isn't installed).

This image downloads data from the internet and runs it as root. The data is not signed or checked before doing so. Consequently, MITM attacks can compromise your system when building the image. In the java image, every command in the dockerfile must be run as root, since it is installing system packages. It is not a security hole in the java image. It is in the clojure image.

If I was packaging clojure, I would have installed a system package for clojure on top of a jdk8 image and been done with it. If I was packaging leiningen, I would have created a leiningen user to download and install it, since no system package exists, and used lein as an entrypoint.

It doesn't bother me that this image does not take the approach that I would, since I can just use something else. It does bother me that when I take the time to try to protect other users, instead of responding to the issues I raise, I am called an :eggplant:. You should have lead with your commentary on why you don't believe running as root is a security hole.

**Comment by md5** [comment]
My apologies for the :eggplant: thing. It was uncalled for and in fact made me look like an :eggplant:. I should have apologized as soon as I realized that, which was pretty much immediately.

It seems like your immediate concern is actually the lack of an integrity check on the `lein` download? I agree that that should be added. If that check were there, I'm having a hard time imagining a threat scenario, but that could very well just be my lack of imagination.

**Comment by md5** [comment]
It looks like `lein` already distributes a GPG signature, so that would be a pretty easy first step.

**Comment by ToBeReplaced** [comment]
@md5 - no problem. Yeah, a gpg check would be a start, assuming we are okay with lein itself downloading and running things from the internet; I haven't looked to see if it performs integrity checks as well. Also, removing `LEIN_ROOT` so that when a user tries to run lein from the image without changing the user, lein's native warning shows in the logs. If the user still wants to override, they can pass in the environment variable.

**Comment by md5** [comment]
I had some free time after lunch today and started to look at GPG verification of the leiningen download: https://github.com/appropriate/docker-clojure/commit/41d02fc48787697abc553e6ea3a4b6bd13ef4e5e

The problem is that the `lein` script is not part of the signed release artifact, so it wasn't clear what the best approach would be for installing things properly since the install docs don't mention downloading the `lein-*-standalone.zip` file.

Regarding whether Leiningen will verify all the things it downloads from the internet, that seems unlikely. It looks like you can sign and possibly verify artifacts from Clojars (cf. https://github.com/technomancy/leiningen/blob/master/doc/GPG.md), but I don't see how that would work in a reasonable way since the GPG keyring won't have any of the keys needed to verify the dozens of JAR file `lein` downloads in a typical installation.

**Comment by Quantisan** [comment]
Thanks for the discussion. I've created a pull request #7 to address the points raised here. Let me know what you guys think please.
