### ISSUE TITLE
All images have vulnerabilities?

### ISSUE THREAD

**Issue by royaldark** [Quantisan/docker-clojure#41]
Docker reports it has scanned all Clojure images and they have vulnerabilities but gives no further information:

![screenshot from 2018-01-24 12-03-46](https://user-images.githubusercontent.com/1669397/35348770-ab8a2e26-00fe-11e8-8b26-6007a902df20.png)

https://hub.docker.com/r/library/clojure/tags/

Can you comment on this? Does Docker publish additional information about vulnerabilities to your account? Is it an issue with an upstream image? Can the issue be resolved?

**Comment by cap10morgan** [comment]
Sadly no, they don't give us any more information. When I've looked into these in the past they were inherited from the upstream openjdk images. When those are updated Docker Hub automatically rebuilds our images.

If there is anything more proactive we can be doing around vulnerabilities, I would love to do it. I'm just not aware of anything at this point.

**Comment by cap10morgan** [comment]
Closing this for now. If anyone has additional things they recommend we do here, feel free to re-open.
