### ISSUE TITLE
Support new official Clojure CLI tools

### ISSUE THREAD

**Issue by zane** [Quantisan/docker-clojure#45]
Would it make sense to add support for the new [Clojure CLI tools](https://clojure.org/reference/deps_and_cli#_usage)? If so I'd be happy to try to put together a pull request. I would probably try to use the same general approach taken when Boot support was added in #27.

**Comment by DeLaGuardo** [comment]
[PR](https://github.com/Quantisan/docker-clojure/pull/44) is ready and waiting for review

**Comment by keerts** [comment]
Nice, great to see support for tools-deps! 

How long will it take before it gets deployed to dockerhub? It is currently not yet available:

```
○ → docker pull clojure:tools-deps
Error response from daemon: manifest for clojure:tools-deps not found

○ → docker pull clojure:tools-deps-alpine
Error response from daemon: manifest for clojure:tools-deps not found
```
It's not clear to me how the process works from here to a docker image. Does something need merging somewhere upstream to make it official? I am sure  someone is working hard on it already, thanks for that!

**Comment by DeLaGuardo** [comment]
@keerts Keep an eye on this [Pool Request](https://github.com/docker-library/official-images/pull/4270) Publishing to the hub should be done automatically after merging it.

**Comment by keerts** [comment]
Ha, that's how it works! Good to know. I will wait a few days for the image to show up.

Thanks again for the work on this.

**Comment by cap10morgan** [comment]
This is now [available on Docker Hub](https://hub.docker.com/_/clojure/).

**Comment by keerts** [comment]
Found it and already happily using it. Thanks for the effort!
