### ISSUE TITLE
Add Java10 support (well, now probably 11)

### ISSUE THREAD

**Issue by jwhitlark** [Quantisan/docker-clojure#47]
I've been writing up some clojure/kubernetes docs, and while I can detail how to build it, it'd be nice to have a more official image to work with, for the runtime and docker improvements, ability to use jlink, and to clean up the docker file.  See https://github.com/jwhitlark/clj-on-k8s-quickstart/blob/master/minimum-docs/05b-minimal-image.md for an example.

I understand that alpine doesn't package JDK 10, but it would be great if we could get it even if only for debian.

**Comment by luposlip** [comment]
What is the best way to host a Clojure app with Docker and JDK10?

**Comment by luposlip** [comment]
@Quantisan - any input? :)

**Comment by Quantisan** [comment]
@luposlip there's an explosion of JDK version since 10. @jwhitlark started an attempt to handle that with #51. We could use some help to iron the template out.

**Comment by Quantisan** [comment]
Looks like #51 might take some time to get sorted out. In the mean time, for anyone else landing here from search, I suggest a multi-stage Dockerfile to compile within a Clojure image and then ditching that to run your Uberjar directly with an OpenJDK image. Example:

```
FROM clojure:alpine as builder
WORKDIR /app
ADD . /app
RUN lein uberjar

FROM openjdk:10-jre-alpine
WORKDIR /root/
EXPOSE 5000
COPY --from=builder /app/target/server.jar .
CMD ["java", "-cp", "server.jar", "clojure.main", "-m", "my-app.main"]
```

Replace `/app/target/server.jar` with path to your uberjar.

**Comment by Quantisan** [comment]
for reference, Clojure is considering skipping Java 9/10 and jumping to 11 LTE. https://clojureverse.org/t/java-10-announcement-implications-for-clojure/1583/14

**Comment by luposlip** [comment]
Thanks @Quantisan - what I have in my Dockerfile now is this - works pretty good with JDK 11 so far:
```
FROM clojure:alpine as builder
MAINTAINER "luposlip@gmail.com"
WORKDIR /app
ADD . /app
RUN lein uberjar

FROM openjdk:11-jre-slim
WORKDIR /root/
EXPOSE 3000
COPY --from=builder /app/target/sample.jar .
CMD ["java", "-cp", "sample.jar", "clojure.main", "-m", "sample.core"]
```

**Comment by jwhitlark** [comment]
Just FYI, since the clojure:alpine builder is using JDK8, I believe there
are issues using compile time JDK11 features like modules or certain new
API's.  YMMV, but I wanted to speed up your debug if you run into any
related issues.

~J

**Comment by luposlip** [comment]
So far, no issues. But thanks for the input - might be needed later @jwhitlark.

**Comment by jwhitlark** [comment]
So, I'm looking at this again, and the newest update.sh from openJDK looks pretty rough to hack on, not to mention the *3 combinatorics (lein, boot, tools.deps).  There's no way I'd have time to setup the tests necessary for all those combinations.

What's the minimum we can do? I'm thinking one full and one slim (openJDK) for each target.  Either that or we figure out how to break these up by interested community, and fan out the maintenance.

**Comment by cap10morgan** [comment]
@jwhitlark Yeah, I agree it's tricky. I'm going to hopefully spend a little thinking some of this through today. We may need some more advanced tooling around this now... If only we had a really awesome programming language we could use... ;)

**Comment by cap10morgan** [comment]
I've got something cooking over on the [clojure-build-system branch](https://github.com/Quantisan/docker-clojure/tree/clojure-build-system).

It's already building all the images we build today (except for `onbuild` variants; that's been deprecated for some time and it's time to stop providing them) plus JDK 11 variants of the Debian-based ones (since there is no JDK 11 Alpine openjdk image upstream).

I need to add in a few more things, maybe some tests, then PR it and see what @Quantisan thinks. :)

**Comment by jwhitlark** [comment]
The stuff you're doing looks really cool, but I'm kinda worried about how well upstream is doing, and what they might change in the future.
So, adoptopenjdk has some alpine 11 images, somehow: adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.28-slim
But event the portola project, while they're providing 12-dev versions, don't commit to providing it in production.

I'm been playing around, and I'm really starting to like the idea of a builder image that contains all three tools, then encouraging multi-stage builds and jlink to get smaller final images out of the process.  So much time gets burned fiddling with some of this stuff, I'm thinking that just giving people a single clj1.9-jdk11 image to start from would be a win.

Alpine is cool and all, but your frequently run into the glibc compatibility issues, and when you add that to their intermittent support of java....
