### ISSUE TITLE
Update Docker Library clojure blurb for new tools-deps from #44

### ISSUE THREAD

**Issue by Quantisan** [Quantisan/docker-clojure#48]
Add some content outlining tools-deps use here https://github.com/docker-library/docs/blob/b07dbefe5bca98b8f2c3d5d23e925720b7441205/clojure/content.md

As suggested in https://github.com/docker-library/official-images/pull/4270#issuecomment-383156596

**Comment by cap10morgan** [comment]
@Quantisan Let me know what you think of this PR: 
https://github.com/docker-library/docs/pull/1354

**Comment by cap10morgan** [comment]
That PR was merged.
