### ISSUE TITLE
tools-deps images should have rlwrap installed

### ISSUE THREAD

**Issue by hkupty** [Quantisan/docker-clojure#52]
Despite being installed, `clj` is not able to run without `rlwrap`.

I'm using this image to run tests on a CI and, because `clj` does not fail when `rlwrap`is not installed but instead aborts with exit code 0, tests appear to pass erroneously.

**Comment by ghadishayban** [comment]
You can use `clojure` instead of `clj`, which is probably better anyways on CI.  (The only thing clj adds is rlwrap for interactive terminals).

`rlwrap` needs perl, which might add a bit of unnecessary dependencies to the image.

**Comment by hkupty** [comment]
I see... That makes sense.. Thanks for answering.

Cheers,
Henry
