### ISSUE TITLE
"No matching manifest for unknown in the manifest list entries" after latest update

### ISSUE THREAD

**Issue by tylerwilding-wk** [Quantisan/docker-clojure#59]
Hello, we seem to no longer be able to pull any clojure image after the latest update.

```bash
❯ docker pull clojure
Using default tag: latest
latest: Pulling from library/clojure
no matching manifest for unknown in the manifest list entries
```

```bash
❯ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

Error on pure-linux environment
```bash
lein-2.8.1: Pulling from library/clojure
no matching manifest for linux/amd64 in the manifest list entries
```

## Repro Steps

run `docker pull clojure`

## Workaround

Using previous tags such as `clojure:lein-2.8.0`

**Comment by sfertman** [comment]
Whatever changed completely broke our CI! 
None of the tags for target/openjdk-8/debian/lein don't work. Alpine seems ok.

**Comment by cap10morgan** [comment]
Sorry about this everyone. I suspect it may be related to an issue with gpg in Debian. Hopefully the latest code on master fixes it. I have a PR to merge and release that here: https://github.com/docker-library/official-images/pull/5132

**Comment by RyanBertrand** [comment]
It looks like the fixed was merged.  Any new push to Docker Hub coming?

Thanks!

**Comment by cap10morgan** [comment]
@ryanbertrand https://github.com/docker-library/official-images/pull/5132 has to be merged by the Docker folks.

**Comment by cap10morgan** [comment]
...which _just_ happened. So the fix should be up on Docker Hub shortly.

**Comment by RyanBertrand** [comment]
Thanks @cap10morgan!
