### ISSUE TITLE
Update for clojure cli 442 

### ISSUE THREAD

**Issue by SevereOverfl0w** [Quantisan/docker-clojure#61]
This release is required for us to run our repo due to bug fixes contained within.

**Comment by cap10morgan** [comment]
Working on this now.

**Comment by cap10morgan** [comment]
[Official images PR](https://github.com/docker-library/official-images/pull/5647)

**Comment by cap10morgan** [comment]
@SevereOverfl0w This should be publicly available now.

**Comment by SevereOverfl0w** [comment]
Using this, thanks!
