### ISSUE TITLE
Adding Java 7, 12 and 13-ea versions

### ISSUE THREAD

**Issue by shen-tian** [Quantisan/docker-clojure#62]
It would be really handy if we had official Clojure images for those Java versions, mainly for Docker-based CI use. In particular, CircleCI's clojure images can be expanded to have these.

A lot of Clojure projects still aim to support Java versions less than 8, but it becomes increasingly hard to test these. Similarly, being able to test against the latest (and next) stable versions of Java is very useful.

Base images for all of the above are [provided for Docker](https://hub.docker.com/_/openjdk)

**Comment by tianon** [comment]
Just a word of caution that Java 7 has a very short lifespan at this point.

**Comment by cap10morgan** [comment]
Yeah, I'm not personally in favor of adding a Java 7 build. But the others make sense.

However, the official OpenJDK image (12+ IIRC) has moved to Oracle Linux, so a lot of our build infrastructure would need to be reworked anyway. And I'm concerned about Oracle's licensing changes and have adopted the AdoptOpenJDK builds personally as a result.

@Quantisan What do you think about moving to the new [adoptopenjdk](https://hub.docker.com/u/adoptopenjdk) upstream images for all of our builds? They don't have JDK 13 EA builds (yet?), but they do have 8-12 and Alpine variants for all of them.

**Comment by Quantisan** [comment]
@cap10morgan good catch on openjdk docker image now ships with oracle linux. moving to adoptopenjdk sounds good to me. we will need to make sure that the Docker tags say `adoptopenjdk` and leave a readme note on not distributing openjdk.

**Comment by cap10morgan** [comment]
Yeah, sounds good. I will make an announcement about the change on the clojure mailing list too.

Currently I'm trying to make PGP sig verification of lein downloads more reliable in the build process. It fails more often than it succeeds currently. Sort of a separate issue, but hard to verify new builds are working correctly if you can't build them. :/

I'm trying out the [pgp-happy-eyeballs](https://github.com/tianon/pgp-happy-eyeballs) proxy but without much success so far.

**Comment by tianon** [comment]
I think https://github.com/docker-library/openjdk/pull/322 is relevant to mention here, especially the following from [the `naughty-from.sh` script](https://github.com/docker-library/official-images/blob/master/naughty-from.sh):

 - clojure:openjdk-11-boot (FROM openjdk:11) [arm32v5, arm32v7, i386, ppc64le, s390x]
 - clojure:openjdk-11-lein (FROM openjdk:11) [arm32v5, arm32v7, i386, ppc64le, s390x]
 - clojure:openjdk-11-tools-deps (FROM openjdk:11) [arm32v5, arm32v7, i386, ppc64le, s390x]
 - clojure:openjdk-8-boot (FROM openjdk:8) [arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x]
 - clojure:openjdk-8-boot-alpine (FROM openjdk:8-alpine) -- completely unsupported base!
 - clojure:openjdk-8-lein (FROM openjdk:8) [arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x]
 - clojure:openjdk-8-lein-alpine (FROM openjdk:8-alpine) -- completely unsupported base!
 - clojure:openjdk-8-tools-deps (FROM openjdk:8) [arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x]
 - clojure:openjdk-8-tools-deps-alpine (FROM openjdk:8-alpine) -- completely unsupported base!
