### ISSUE TITLE
Provide named Debian variants

### ISSUE THREAD

**Issue by iarenaza** [Quantisan/docker-clojure#67]
Debian Buster has been out since a few months ago and is the current stable version. But Debian Stretch will still be maintained (as `oldstable`) for several months (in theory until 12 months later than Buster official release date).

OpenJDK already provides named Debian variants (e.g., `openjdk:8-stretch`, `openjdk:8-slim-buster[1]`), with `openjdk:8`, `openjdk:8-jre` and `openjdk:8-jdk` defaulting to Debian Stretch as of today (see [2]). But they also warn that "...you'll likely want to specify one of these[3] explicitly to minimize breakage when there are new releases of Debian."

So using `openjdk:8` as the base to to build the Debian-based Clojure images has the risk of suddenly changing Debian distribution when the OpenJDK Docker image maintainers change the Debian release they point to for the `openjdk:8` tag.

I think it would be a good idea to build images for both the Stretch and Buster (and in the general case for `stable` and `oldstable` versions of Debian at that point) and tag them using a similar naming structure than the OpenJDK Docker images (to make it easier to know which image they are based on). That would allow each user to decide whether they want to use one of the other, and migrate from the older one to the when they mean it (as opposed to migrating by simply pulling the same image tag at a later time).

[1] They seem to have change naming patterns for newer Debian releases, as there is no  `stretch` tag having the `slim` part in them, while all `buster` tags have the `slim` part in them.
[2] https://github.com/docker-library/docs/blob/master/openjdk/README.md#shared-tags
[3] They refer to images whose tags may have names like buster or stretch in them. These are the suite code names for releases of Debian and indicate which release the image is based on.

**Comment by cap10morgan** [comment]
Good suggestion. I'll keep this in mind as I rework our build system for #66 & #68. Thanks!
