### ISSUE TITLE
Consider including make with tools-deps images

### ISSUE THREAD

**Issue by danskarda** [Quantisan/docker-clojure#76]
It is helpful to write down clojure commands which are common in tools-deps project. Some projects keep track of commands in good old Makefiles. 

This makes sense as you do not have to remember all commands parameters and repeat them in CI files etc. For example figwheel.main has one Makefile in repo. 

Please consider including GNU makefile in tools-deps image. It has no dependencies except libc and is small (~1.3M uncompressed size of Debian package). With make you can use the image with CI workflows without the need to repeat all clojure commands and its -A -R  -C parameters.

Thank you.

**Comment by cap10morgan** [comment]
@Quantisan I'm 👍 on this if you are.

**Comment by Quantisan** [comment]
@cap10morgan sounds good to me too. Thanks @danskarda for making a clear case.

**Comment by cap10morgan** [comment]
I'll go ahead and push this to #78 then.

**Comment by cap10morgan** [comment]
Added in #79
