### ISSUE TITLE
openjdk-14-tools-deps-alpine does not have bash

### ISSUE THREAD

**Issue by danskarda** [Quantisan/docker-clojure#77]
Clojure script starts with:

```
#!/usr/bin/env bash
```

Unfortunately bash is not present in alpine image. This image cannot run `clojure` script.

**Comment by cap10morgan** [comment]
It certainly tries to include it: https://github.com/Quantisan/docker-clojure/blob/be736864bf3e6d35c1bc6b13fd2add4a319fb92b/target/openjdk-14-alpine/tools-deps/Dockerfile#L8

But I was able to replicate the bug with `docker run --rm -ti clojure:openjdk-14-tools-deps-alpine` which gave me this error: `env: can't execute 'bash': No such file or directory`.

And inside a container started with `sh` instead, `which bash` doesn't find anything. The installation command succeeds in there, however.

Hmm...

**Comment by tianon** [comment]
Look down a couple lines: https://github.com/Quantisan/docker-clojure/blob/be736864bf3e6d35c1bc6b13fd2add4a319fb92b/target/openjdk-14-alpine/tools-deps/Dockerfile#L13

**Comment by cap10morgan** [comment]
@tianon D'oh! Yep, that'll do it. Thanks!

**Comment by cap10morgan** [comment]
Ultimately the issue here is that I have bash as a build dep rather than a runtime dep in the alpine tools-deps images. Pushing a fix shortly.
