### ISSUE TITLE
bash: clojure: command not found

### ISSUE THREAD

**Issue by jiyinyiyong** [Quantisan/docker-clojure#80]
While the name of the repo says it's a Docker image for Clojure, I can't find the command `clojure`...

```
dev-machine=>> docker pull clojure
Using default tag: latest
latest: Pulling from library/clojure
Digest: sha256:d53533c852b0df4cc07d9318c87ffab2a75635f8a07afea952949e58dbb2dffb
Status: Image is up to date for clojure:latest
dev-machine=>> docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
timbru31/java-node     latest              47abf232ad53        2 days ago          434MB
clojure                latest              9a970b718838        6 days ago          431MB
clojure                slim-buster         9a970b718838        6 days ago          431MB
dev-machine=>> docker run -i -t clojure /bin/bash
root@db61bf95fd51:/tmp# clj
bash: clj: command not found
root@db61bf95fd51:/tmp# clojure
bash: clojure: command not found
root@db61bf95fd51:/tmp# lein
Leiningen is a tool for working with Clojure projects.

Several tasks are available:
```

```
dev-machine=>> docker run -i -t clojure:latest /bin/bash
root@018f6774f5b1:/tmp# clj
bash: clj: command not found
```

Nowadays many build tools are based on Clojure and I see `clojure` commands in the code too..

https://github.com/Quantisan/docker-clojure/blob/master/clean.sh#L5

Anything wrong on my side? Or is it just a lein image?

**Comment by cap10morgan** [comment]
You want the `clojure:tools-deps` variant. Leiningen predates tools-deps and was the de facto Clojure CLI tool before that. So the bare `clojure` image has always just provided lein.

@Quantisan maybe we should consider providing lein, boot, and tools-deps in the `clojure` image? That would still allow people to get leaner images with only the tools they want by using more specific tags. And it wouldn’t break anything relying on lein being in the bare image.

**Comment by jiyinyiyong** [comment]
Cool. Thanks. No confusion this time~

```
dev-machine=>> docker run -i -t clojure:tools-deps /bin/bash
root@d900f25c275c:/tmp# clj
Please install rlwrap for command editing or use "clojure" instead.
root@d900f25c275c:/tmp# clojure
Clojure 1.10.1
user=>
```

**Comment by Quantisan** [comment]
@cap10morgan Are you saying to add a `clojure:default` which includes all 3 build tools? And then keep the specific tags, e.g. `clojure:lein`, with only the specified build tool? That sounds good to me.

**Comment by cap10morgan** [comment]
Yeah basically. So `clojure` & `clojure:latest` would contain all three tool sets (maybe others? don’t have the list in front of me).

**Comment by Quantisan** [comment]
@cap10morgan going with just the 3 for `:latest` sounds good enough. Those are the most popular build tools.
