### ISSUE TITLE
Stale clojure:latest

### ISSUE THREAD

**Issue by njordhov** [Quantisan/docker-clojure#89]
> As of 2020-3-20 the clojure:latest (also clojure because latest is the default) now has leiningen, boot, and tools-deps installed.

However, when I build a container based on `clojure:latest` it seems to use an older image that doesn't include tools-deps. Inspecting the image reports it to be created before 2020-03-20:

    docker image inspect clojure:latest | grep Created

=>

    "Created": "2020-02-02T21:36:26.419382898Z"

Is it perhaps the case that the `clojure:latest` distribution has not yet been updated?

**Comment by tianon** [comment]
Looking at https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/clojure/, it appears it has been failing to build. :disappointed:

**Comment by tianon** [comment]
... can you tell I have a really good memory?  Just re-found https://github.com/docker-library/official-images/pull/7601. :sweat_smile: :heart:

**Comment by njordhov** [comment]
See also #80

**Comment by cap10morgan** [comment]
We’re currently waiting to see if @technomancy will upload his PGP key to keys.openpgp.org. See this leiningen issue for more details: https://github.com/technomancy/leiningen/issues/2681

**Comment by cap10morgan** [comment]
Fixed by #90. Will update the official library PR shortly.
